# Generated by Django 3.2.9 on 2021-11-19 20:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NONE', max_length=50)),
                ('agua', models.IntegerField(default=0)),
                ('arena', models.IntegerField(default=0)),
                ('grava', models.IntegerField(default=0)),
                ('cemento', models.IntegerField(default=0)),
                ('aditivo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NONE', max_length=50)),
                ('slug', models.SlugField(max_length=250)),
                ('agua', models.FloatField(default=0)),
                ('arena', models.FloatField(default=0)),
                ('grava', models.FloatField(default=0)),
                ('cemento', models.FloatField(default=0)),
                ('aditivo', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='logic_api.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NONE', max_length=50)),
                ('slug', models.SlugField(max_length=250)),
                ('measure', models.IntegerField()),
                ('destination', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic_api.clients')),
                ('mixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic_api.mixtures')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='rol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logic_api.rols'),
        ),
    ]
