# Generated by Django 3.2.9 on 2021-11-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_api', '0002_auto_20211122_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mixtures',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
